fixtures:
  repositories:
    "stdlib":
      "repo": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "concat":
      "repo": "git://github.com/puppetlabs/puppetlabs-concat.git"
  symlinks:
    "unbound": "#{source_dir}"
